### ISSUE TITLE
push時のデプロイ対象をmasterブランチのみにする

### ISSUE THREAD

**Issue by ioapm** [ioapm/myblog#4]
https://circleci.com/docs/2.0/configuration-reference/#branches

```
jobs:
  build:
    branches:
      only:
        - master
```
